version: '3.9'

networks:
  sc:
    name: global
    external: true
  global:
    external: true

services:
  shoppingcart_db:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "shopping_cart"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./storage/shoppingcart/db:/var/lib/postgres/data
    networks:
      - sc
      - global
    hostname: shoppingcart_db

  keycloak_db:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"
    volumes:
      - ./storage/keycloak/db:/var/lib/postgres/data
    networks:
      - sc
      - global
    hostname: keycloak_db

  keycloak:
    image: bitnami/keycloak:22.0.5-debian-11-r2
    environment:
      KEYCLOAK_ADMIN_USER: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_DATABASE_VENDOR: "postgresql"
      KEYCLOAK_DATABASE_HOST: "keycloak_db"
      KEYCLOAK_DATABASE_PORT: "5432"
      KEYCLOAK_DATABASE_NAME: "keycloak"
      KEYCLOAK_DATABASE_USER: "admin"
      KEYCLOAK_DATABASE_PASSWORD: "admin"
      KEYCLOAK_HTTP_PORT: 8081
    ports:
      - "8081:8081"
      - "8443:8443"
    networks:
      - sc
      - global
    hostname: keycloak
    depends_on:
      - keycloak_db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
        - "80:80"
    networks:
      - sc
      - global
    hostname: pgadmin
    depends_on:
      - shoppingcart_db
      - keycloak_db
