version: '3.9'

networks:
  sc:
    name: global
    external: true
  global:
    external: true

services:
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "shopping_cart"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres_data:/var/lib/postgres/data
    networks:
      - sc
      - global

  keycloak:
    image: bitnami/keycloak:22.0.5-debian-11-r2
    environment:
      KEYCLOAK_ADMIN_USER: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_DATABASE_VENDOR: "postgresql"
      KEYCLOAK_DATABASE_HOST: "postgres"
      KEYCLOAK_DATABASE_PORT: "5432"
      KEYCLOAK_DATABASE_NAME: "keycloak"
      KEYCLOAK_DATABASE_USER: "admin"
      KEYCLOAK_DATABASE_PASSWORD: "admin"
    ports:
      - "8081:8080"
      - "8443:8443"
    networks:
      - sc
      - global

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
        - "80:80"
    networks:
      - sc
      - global