version: '3.9'

networks:
  sc:
    name: global
    external: true
  global:
    external: true

services:
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "shopping_cart"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres_data:/var/lib/postgres/data
    networks:
      - sc
      - global

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
        - "80:80"
    networks:
      - sc
      - global